language: node_js
node_js:
- node
- '6'
- '4'
deploy:
  provider: npm
  email: marcus@stade.se
  skip_cleanup: true
  api_key:
    secure: V4yhKQimtBjwkMdeZgGuqh8brQASULGr2BFPGjMec/HhoYfUcgZ8MGrOpj+RgJUxckvr7jZYskQkWTUiBhK+Lof/MkOpKjh2N0E1R5Ka8Pc45WuRUffnSP5RSluLvz6Wfi/ArHS/CKUu8sbamtTyC8d00MpY99i165qDj36HBllWtaz9RPMsWfr1EB8Vc3WL7w+nfKN/hLnB0KMyY31EWMlIkvyuE9+Rym6jazZqmQSlpPQVImypws1OZgNNix2EW99nW9Fo11hWnG+s1s3/SuWTBsR41XZlkbC6J7rNrAKL/23PMBFECQ8Lmxvq0tDWC+ZGFU15aQzVtbHpFCueX/k/LhuAYH11nbsrGtXdzp5RwVP+qFWUf1TyvfkZW3Nvape0P8H7zBsWTN+weuuWfl1NGc7E+Sfz1cE428gCm8pjXz8MSrqJMrSbN+Qw3VIIBp/kU1WdeggW7Qh8grrnX8VB9sWApJXQaKqQmtyvFSZxOii0MbLX9/Oe0790LEl5ihoeOiLirDRRA/7YQs7p60N8q2/3jBaQmGkrP/Emz+jiDyYNUJebdy4mDBC4meuYsV31LYGE050sMvWT5X0oCFYygpctTt7l35tD34dUFoxdlj733Ci764RzmDV+UlrB0gSF5KuLHbO/GBtS2v8NzGLJkQ0lqfOq+kbWVq3nMj8=
  on:
    tags: true
    repo: zambezi/react-simple-table
    all_branches: true
